services:
  db:
    image: mysql:8.4
    container_name: analytics-mysql
    command: ["mysqld", "--local-infile=1"]
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: admin
      MYSQL_PASSWORD: analytics

    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-prootpassword"]
      interval: 10s
      retries: 6
      timeout: 5s

  app:
    build: .
    image: query-execution-service:latest
    container_name: query-execution-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://db:3306/analytics
      DB_USERNAME: admin
      DB_PASSWORD: analytics
      APP_JWT_SECRET: change-me-please-change-me-please-1234567890
      MYSQL_DATABASE: analytics
    ports:
      - "8080:8080"
